=== crocs-muni/ECTester/src/cz/crcs/ectester/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- /<category>/curves.xml -->

    <xs:simpleType name="fieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prime"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="data" abstract="true"/>
    <xs:element name="file" substitutionGroup="data" type="xs:string"/>
    <xs:element name="inline" substitutionGroup="data" type="xs:string"/>

    <xs:complexType name="curveType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="bits" type="xs:positiveInteger"/>
            <xs:element name="field" type="fieldType"/>
            <xs:element ref="data" />
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="curves">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curve" type="curveType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/keys.xml -->

    <xs:complexType name="keyType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element ref="data" />
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="keys">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="keypair" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="privkey" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="pubkey" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/results.xml -->

    <xs:simpleType name="kaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DH"/>
            <xs:enumeration value="DHC"/>
            <xs:enumeration value="DH_PLAIN"/>
            <xs:enumeration value="DHC_PLAIN"/>
            <xs:enumeration value="PACE_GM"/>
            <xs:enumeration value="DH_PLAIN_XY"/>
            <xs:enumeration value="ANY"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="kaResultType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="ka" type="kaType"/>
            <xs:element ref="data" />
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="onekey" type="xs:string"/>
            <xs:element name="otherkey" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="sigType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SHA1"/>
            <xs:enumeration value="SHA224"/>
            <xs:enumeration value="SHA256"/>
            <xs:enumeration value="SHA384"/>
            <xs:enumeration value="SHA512"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sigResultType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="sig" type="sigType"/>
            <xs:element ref="data"/>
            <xs:element name="raw" type="xs:string" minOccurs="0"/>
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="signkey" type="xs:string"/>
            <xs:element name="verifykey" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="results">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kaResult" type="kaResultType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="sigResult" type="sigResultType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /categories.xml -->

    <xs:complexType name="categoryType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="directory" type="xs:string"/>
            <xs:element name="desc" minOccurs="0" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" type="categoryType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== crocs-muni/ECTester/common/src/main/java/cz/crcs/ectester/data/x962/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>prime192v1</id>
        <bits>192</bits>
        <field>prime</field>
        <file>prime192v1.csv</file>
    </curve>
    <curve>
        <id>prime192v2</id>
        <bits>192</bits>
        <field>prime</field>
        <file>prime192v2.csv</file>
    </curve>
    <curve>
        <id>prime192v3</id>
        <bits>192</bits>
        <field>prime</field>
        <file>prime192v3.csv</file>
    </curve>

    <curve>
        <id>prime239v1</id>
        <bits>239</bits>
        <field>prime</field>
        <file>prime239v1.csv</file>
    </curve>
    <curve>
        <id>prime239v2</id>
        <bits>239</bits>
        <field>prime</field>
        <file>prime239v2.csv</file>
    </curve>
    <curve>
        <id>prime239v3</id>
        <bits>239</bits>
        <field>prime</field>
        <file>prime239v3.csv</file>
    </curve>

    <curve>
        <id>prime256v1</id>
        <bits>256</bits>
        <field>prime</field>
        <file>prime256v1.csv</file>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/categories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <!-- Standard curves -->
    <category>
        <name>anomalous</name>
        <directory>anomalous</directory>
        <desc>These prime field curves have the same order as the field order. Some are from https://dspace.jaist.ac.jp/dspace/bitstream/10119/4464/1/73-61.pdf.</desc>
    </category>
    <category>
        <name>brainpool</name>
        <directory>brainpool</directory>
        <desc>ECC Brainpool Standard Curves and Curve Generation v. 1.0  19.10.2005</desc>
    </category>
    <category>
        <name>nist</name>
        <directory>nist</directory>
        <desc>RECOMMENDED ELLIPTIC CURVES FOR FEDERAL GOVERNMENT USE  July 1999</desc>
    </category>
    <category>
        <name>secg</name>
        <directory>secg</directory>
        <desc>SEC 2: Recommended Elliptic Curve Domain Parameters version 2.0  January 27, 2010</desc>
    </category>
    <category>
        <name>anssi</name>
        <directory>anssi</directory>
        <desc>Agence nationale de la sécurité des systèmes d'information: Publication d'un paramétrage de courbe elliptique visant des applications de passeport électronique et de l'administration électronique française. 21 November 2011</desc>
    </category>
    <category>
        <name>GOST</name>
        <directory>gost</directory>
        <desc>GOST R 34.10-2001: RFC5832</desc>
    </category>
    <category>
        <name>x962</name>
        <directory>x962</directory>
        <desc>ANSI X9.62 example curves.</desc>
    </category>
    <category>
        <name>Barreto-Naehrig</name>
        <directory>bn</directory>
        <desc>Barreto-Naehrig curves from: A Family of Implementation-Friendly BN Elliptic Curves - https://eprint.iacr.org/2010/429.pdf.</desc>
    </category>
    <category>
        <name>MNT</name>
        <directory>mnt</directory>
        <desc>MNT (Miyaji, Nakabayashi, and Takano) example curves from: New explicit conditions of elliptic curve traces for FR-reduction - https://dspace.jaist.ac.jp/dspace/bitstream/10119/4432/1/73-48.pdf.</desc>
    </category>
    <category>
        <name>other</name>
        <directory>other</directory>
        <desc>An assortment of some other curves.</desc>
    </category>

    <!-- Custom curves -->
    <category>
        <name>invalid</name>
        <directory>invalid</directory>
        <desc>Invalid curves and points on them for common standard named curves.</desc>
    </category>
    <category>
        <name>twist</name>
        <directory>twist</directory>
        <desc>Points on quadratic twists of common standard named curves.</desc>
    </category>
    <category>
        <name>degenerate</name>
        <directory>degenerate</directory>
        <desc>Points on degenerate curves for common standard named curves.</desc>
    </category>
    <category>
        <name>cofactor</name>
        <directory>cofactor</directory>
        <desc>Curves of order n * p, with p prime and n in {2,4,8,16,32,64,128}. Generator of order p, with points on the subgroup of order n.</desc>
    </category>
    <category>
        <name>composite</name>
        <directory>composite</directory>
        <desc>Composite order curves, with points of very small order pre-generated. Also curves with order of a product of two large primes.</desc>
    </category>
    <category>
        <name>wrong</name>
        <directory>wrong</directory>
        <desc>Wrong field curves and other wrong parameters. These should definitely give an error when used. Since the "prime" used for the field is not prime, and the field polynomials are also not irreducible. Simply put these parameters don't specify a valid elliptic curve.</desc>
    </category>
    <category>
        <name>test</name>
        <directory>test</directory>
        <desc>Test vectors</desc>
    </category>
    <category>
        <name>wycheproof</name>
        <directory>wycheproof</directory>
        <desc>Test cases from google Wycheproof project: https://github.com/google/wycheproof</desc>
    </category>
	<category>
        <name>supersingular</name>
        <directory>supersingular</directory>
        <desc>Some supersingular curves, over F_p with order equal to p + 1.</desc>
    </category>
    <category>
        <name>misc</name>
        <directory>misc</directory>
        <desc>Miscellaneous data.</desc>
    </category>
</categories>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/anomalous/curves.xml
<?xml version="1.0" encoding="UTF-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
	<curve>
		<id>miyaji128a1</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128a1.csv</file>
		<desc>First curve in the "Proposed scheme A" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128a2</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128a2.csv</file>
		<desc>Second curve in the "Proposed scheme A" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128b1</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128b1.csv</file>
		<desc>First curve in the "Proposed scheme B" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128b2</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128b2.csv</file>
		<desc>Second curve in the "Proposed scheme B" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>anomalous112</id>
		<bits>112</bits>
		<field>prime</field>
		<file>anomalous112.csv</file>
	</curve>
    <curve>
        <id>anomalous128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>anomalous128.csv</file>
    </curve>
    <curve>
        <id>anomalous160</id>
        <bits>160</bits>
        <field>prime</field>
        <file>anomalous160.csv</file>
    </curve>
    <curve>
        <id>anomalous192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>anomalous192.csv</file>
    </curve>
    <curve>
        <id>anomalous224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>anomalous224.csv</file>
    </curve>
    <curve>
        <id>anomalous256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>anomalous256.csv</file>
    </curve>
    <curve>
        <id>anomalous320</id>
        <bits>320</bits>
        <field>prime</field>
        <file>anomalous320.csv</file>
    </curve>
    <curve>
        <id>anomalous384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>anomalous384.csv</file>
    </curve>
    <curve>
        <id>anomalous512</id>
        <bits>512</bits>
        <field>prime</field>
        <file>anomalous512.csv</file>
    </curve>
    <curve>
        <id>anomalous521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>anomalous521.csv</file>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/supersingular/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>ss128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>ss128.csv</file>
        <desc>Supersingular curve</desc>
    </curve>
    <curve>
        <id>ss192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>ss192.csv</file>
        <desc>Supersingular curve</desc>
    </curve>
    <curve>
        <id>ss224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>ss224.csv</file>
        <desc>Supersingular curve</desc>
    </curve>
    <curve>
        <id>ss256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>ss256.csv</file>
        <desc>Supersingular curve</desc>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/misc/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd">
    <privkey>
        <id>openssl-bug/skey</id>
        <inline>0x4543A4D2C9DDD5516FD16D5498034C76D4EAB340276B6BAD8FF57756F4ECA8E6</inline>
        <curve>secg/secp256r1</curve>
    </privkey>
    <pubkey>
        <id>openssl-bug/pkey</id>
        <inline>0x296D416994A4801B9A48E8C67C98E0C05DE1C0E85D4DC676F32FEACDC4998F0E,0xA91F9BE06C1D50EEB0295A35CA0F130F17EA647147626318E28AEC97F0653749</inline>
        <curve>secg/secp256r1</curve>
    </pubkey>

    <pubkey>
        <id>compression/128/non-residue</id>
        <inline>0xb6707fa8afeddf79b9579e8dda4eaf51,0x000000000000000000000000000000</inline>
        <curve>secg/secp128r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/160/non-residue</id>
        <inline>0xb1cb90992ff28689c6f160dcfb51b9525492e3d9,0x0000000000000000000000000000000000000000</inline>
        <curve>secg/secp160r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/192/non-residue</id>
        <inline>0x8910baef94195e069c142b129e97507bfc2e19b53b707441,0x000000000000000000000000000000000000000000000000</inline>
        <curve>secg/secp192r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/224/non-residue</id>
        <inline>0xafd44b41555e8bea506518b35405d4f5be78355d6342e7f5287bd748,0x00000000000000000000000000000000000000000000000000000000</inline>
        <curve>secg/secp224r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/256/non-residue</id>
        <inline>0xeb7a88c476ede6ecae7909aa19631d9918762e851c38a3ea00fe50b7b2e2e656,0x0000000000000000000000000000000000000000000000000000000000000000</inline>
        <curve>secg/secp256r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/384/non-residue</id>
        <inline>0x45d50b222c11c0f20946133382a988caf2d4f64e669340ba60a5ab3151a6bf3883e7e77a6d358fd07db411bc8ad0f375,0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</inline>
        <curve>secg/secp384r1</curve>
    </pubkey>
    <pubkey>
        <id>compression/521/non-residue</id>
        <inline>0x1d7b127de8415bbf498c26f7a17c9e39dcd866b68359bc8e139f401f8ee8489419fb6166850c98cce7e1fdc620902961656d72f9b42703f06ccb9fe6e218e7e3fe3,0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000</inline>
        <curve>secg/secp521r1</curve>
    </pubkey>
</keys>

=== crocs-muni/ECTester/common/src/main/java/cz/crcs/ectester/data/mnt/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>mnt1</id>
        <bits>170</bits>
        <field>prime</field>
        <file>mnt1.csv</file>
        <desc>Example 1</desc>
    </curve>
    <curve>
        <id>mnt2/1</id>
        <bits>159</bits>
        <field>prime</field>
        <file>mnt2_1.csv</file>
        <desc>Example 2/1</desc>
    </curve>
    <curve>
        <id>mnt2/2</id>
        <bits>159</bits>
        <field>prime</field>
        <file>mnt2_2.csv</file>
        <desc>Example 2/2</desc>
    </curve>
    <curve>
        <id>mnt3/1</id>
        <bits>160</bits>
        <field>prime</field>
        <file>mnt3_1.csv</file>
        <desc>Example 3/1</desc>
    </curve>
    <curve>
        <id>mnt3/2</id>
        <bits>160</bits>
        <field>prime</field>
        <file>mnt3_2.csv</file>
        <desc>Example 3/2</desc>
    </curve>
    <curve>
        <id>mnt3/3</id>
        <bits>160</bits>
        <field>prime</field>
        <file>mnt3_3.csv</file>
        <desc>Example 3/3</desc>
    </curve>
    <curve>
        <id>mnt4</id>
        <bits>240</bits>
        <field>prime</field>
        <file>mnt4.csv</file>
        <desc>Example 4</desc>
    </curve>
    <curve>
        <id>mnt5/1</id>
        <bits>240</bits>
        <field>prime</field>
        <file>mnt5_1.csv</file>
        <desc>Example 5/1</desc>
    </curve>
    <curve>
        <id>mnt5/2</id>
        <bits>240</bits>
        <field>prime</field>
        <file>mnt5_2.csv</file>
        <desc>Example 5/2</desc>
    </curve>
    <curve>
        <id>mnt5/3</id>
        <bits>240</bits>
        <field>prime</field>
        <file>mnt5_3.csv</file>
        <desc>Example 5/3</desc>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/java/cz/crcs/ectester/data/test/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd">
    <keypair>
        <id>secp160r1-U</id>
        <file>secg/secp160r1-keyU.csv</file>
        <curve>secg/secp160r1</curve>
    </keypair>
    <keypair>
        <id>secp160r1-V</id>
        <file>secg/secp160r1-keyV.csv</file>
        <curve>secg/secp160r1</curve>
    </keypair>
    <keypair>
        <id>sect163k1-U</id>
        <file>secg/sect163k1-keyU.csv</file>
        <curve>secg/sect163k1</curve>
    </keypair>
    <keypair>
        <id>sect163k1-V</id>
        <file>secg/sect163k1-keyV.csv</file>
        <curve>secg/sect163k1</curve>
    </keypair>

    <keypair>
        <id>brainpoolP224r1-A</id>
        <file>brainpool/brainpoolP224r1-keyA.csv</file>
        <curve>brainpool/brainpoolP224r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP224r1-B</id>
        <file>brainpool/brainpoolP224r1-keyB.csv</file>
        <curve>brainpool/brainpoolP224r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP256r1-A</id>
        <file>brainpool/brainpoolP256r1-keyA.csv</file>
        <curve>brainpool/brainpoolP256r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP256r1-B</id>
        <file>brainpool/brainpoolP256r1-keyB.csv</file>
        <curve>brainpool/brainpoolP256r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP384r1-A</id>
        <file>brainpool/brainpoolP384r1-keyA.csv</file>
        <curve>brainpool/brainpoolP384r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP384r1-B</id>
        <file>brainpool/brainpoolP384r1-keyB.csv</file>
        <curve>brainpool/brainpoolP384r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP512r1-A</id>
        <file>brainpool/brainpoolP512r1-keyA.csv</file>
        <curve>brainpool/brainpoolP512r1</curve>
    </keypair>
    <keypair>
        <id>brainpoolP512r1-B</id>
        <file>brainpool/brainpoolP512r1-keyB.csv</file>
        <curve>brainpool/brainpoolP512r1</curve>
    </keypair>

    <keypair>
        <id>p192-A</id>
        <file>nist/p192-keyIUT.csv</file>
        <curve>nist/P-192</curve>
    </keypair>
    <pubkey>
        <id>p192-B</id>
        <file>nist/p192-keyCAVS.csv</file>
        <curve>nist/P-192</curve>
    </pubkey>
    <keypair>
        <id>p224-A</id>
        <file>nist/p224-keyIUT.csv</file>
        <curve>nist/P-224</curve>
    </keypair>
    <pubkey>
        <id>p224-B</id>
        <file>nist/p224-keyCAVS.csv</file>
        <curve>nist/P-224</curve>
    </pubkey>
    <keypair>
        <id>p256-A</id>
        <file>nist/p256-keyIUT.csv</file>
        <curve>nist/P-256</curve>
    </keypair>
    <pubkey>
        <id>p256-B</id>
        <file>nist/p256-keyCAVS.csv</file>
        <curve>nist/P-256</curve>
    </pubkey>
    <keypair>
        <id>p384-A</id>
        <file>nist/p384-keyIUT.csv</file>
        <curve>nist/P-384</curve>
    </keypair>
    <pubkey>
        <id>p384-B</id>
        <file>nist/p384-keyCAVS.csv</file>
        <curve>nist/P-384</curve>
    </pubkey>
    <keypair>
        <id>p521-A</id>
        <file>nist/p521-keyIUT.csv</file>
        <curve>nist/P-521</curve>
    </keypair>
    <pubkey>
        <id>p521-B</id>
        <file>nist/p521-keyCAVS.csv</file>
        <curve>nist/P-521</curve>
    </pubkey>
    <keypair>
        <id>b163-A</id>
        <file>nist/b163-keyIUT.csv</file>
        <curve>nist/B-163</curve>
    </keypair>
    <pubkey>
        <id>b163-B</id>
        <file>nist/b163-keyCAVS.csv</file>
        <curve>nist/B-163</curve>
    </pubkey>
    <keypair>
        <id>b233-A</id>
        <file>nist/b233-keyIUT.csv</file>
        <curve>nist/B-233</curve>
    </keypair>
    <pubkey>
        <id>b233-B</id>
        <file>nist/b233-keyCAVS.csv</file>
        <curve>nist/B-233</curve>
    </pubkey>
    <keypair>
        <id>b283-A</id>
        <file>nist/b283-keyIUT.csv</file>
        <curve>nist/B-283</curve>
    </keypair>
    <pubkey>
        <id>b283-B</id>
        <file>nist/b283-keyCAVS.csv</file>
        <curve>nist/B-283</curve>
    </pubkey>
    <keypair>
        <id>b409-A</id>
        <file>nist/b409-keyIUT.csv</file>
        <curve>nist/B-409</curve>
    </keypair>
    <pubkey>
        <id>b409-B</id>
        <file>nist/b409-keyCAVS.csv</file>
        <curve>nist/B-409</curve>
    </pubkey>
    <keypair>
        <id>b571-A</id>
        <file>nist/b571-keyIUT.csv</file>
        <curve>nist/B-571</curve>
    </keypair>
    <pubkey>
        <id>b571-B</id>
        <file>nist/b571-keyCAVS.csv</file>
        <curve>nist/B-571</curve>
    </pubkey>
    <keypair>
        <id>k163-A</id>
        <file>nist/k163-keyIUT.csv</file>
        <curve>nist/K-163</curve>
    </keypair>
    <pubkey>
        <id>k163-B</id>
        <file>nist/k163-keyCAVS.csv</file>
        <curve>nist/K-163</curve>
    </pubkey>
    <keypair>
        <id>k233-A</id>
        <file>nist/k233-keyIUT.csv</file>
        <curve>nist/K-233</curve>
    </keypair>
    <pubkey>
        <id>k233-B</id>
        <file>nist/k233-keyCAVS.csv</file>
        <curve>nist/K-233</curve>
    </pubkey>
    <keypair>
        <id>k283-A</id>
        <file>nist/k283-keyIUT.csv</file>
        <curve>nist/K-283</curve>
    </keypair>
    <pubkey>
        <id>k283-B</id>
        <file>nist/k283-keyCAVS.csv</file>
        <curve>nist/K-283</curve>
    </pubkey>
    <keypair>
        <id>k409-A</id>
        <file>nist/k409-keyIUT.csv</file>
        <curve>nist/K-409</curve>
    </keypair>
    <pubkey>
        <id>k409-B</id>
        <file>nist/k409-keyCAVS.csv</file>
        <curve>nist/K-409</curve>
    </pubkey>
    <keypair>
        <id>k571-A</id>
        <file>nist/k571-keyIUT.csv</file>
        <curve>nist/K-571</curve>
    </keypair>
    <pubkey>
        <id>k571-B</id>
        <file>nist/k571-keyCAVS.csv</file>
        <curve>nist/K-571</curve>
    </pubkey>
</keys>
