=== crocs-muni/ECTester/src/cz/crcs/ectester/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- /<category>/curves.xml -->

    <xs:simpleType name="fieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prime"/>
            <xs:enumeration value="binary"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="data" abstract="true"/>
    <xs:element name="file" substitutionGroup="data" type="xs:string"/>
    <xs:element name="inline" substitutionGroup="data" type="xs:string"/>

    <xs:complexType name="curveType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="bits" type="xs:positiveInteger"/>
            <xs:element name="field" type="fieldType"/>
            <xs:element ref="data" />
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="curves">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curve" type="curveType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/keys.xml -->

    <xs:complexType name="keyType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element ref="data" />
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="keys">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="keypair" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="privkey" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="pubkey" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/results.xml -->

    <xs:simpleType name="kaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DH"/>
            <xs:enumeration value="DHC"/>
            <xs:enumeration value="DH_PLAIN"/>
            <xs:enumeration value="DHC_PLAIN"/>
            <xs:enumeration value="PACE_GM"/>
            <xs:enumeration value="DH_PLAIN_XY"/>
            <xs:enumeration value="ANY"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="kaResultType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="ka" type="kaType"/>
            <xs:element ref="data" />
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="onekey" type="xs:string"/>
            <xs:element name="otherkey" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="sigType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="SHA1"/>
            <xs:enumeration value="SHA224"/>
            <xs:enumeration value="SHA256"/>
            <xs:enumeration value="SHA384"/>
            <xs:enumeration value="SHA512"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sigResultType">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="sig" type="sigType"/>
            <xs:element ref="data"/>
            <xs:element name="raw" type="xs:string" minOccurs="0"/>
            <xs:element name="curve" type="xs:string"/>
            <xs:element name="signkey" type="xs:string"/>
            <xs:element name="verifykey" type="xs:string"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="results">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kaResult" type="kaResultType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="sigResult" type="sigResultType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /categories.xml -->

    <xs:complexType name="categoryType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="directory" type="xs:string"/>
            <xs:element name="desc" minOccurs="0" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" type="categoryType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/secg/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>secp112r1</id>
        <bits>112</bits>
        <field>prime</field>
        <file>secp112r1.csv</file>
    </curve>
    <curve>
        <id>secp112r2</id>
        <bits>112</bits>
        <field>prime</field>
        <file>secp112r2.csv</file>
    </curve>
    <curve>
        <id>secp128r1</id>
        <bits>128</bits>
        <field>prime</field>
        <file>secp128r1.csv</file>
    </curve>
    <curve>
        <id>secp128r2</id>
        <bits>128</bits>
        <field>prime</field>
        <file>secp128r2.csv</file>
    </curve>
    <curve>
        <id>secp160k1</id>
        <bits>160</bits>
        <field>prime</field>
        <file>secp160k1.csv</file>
    </curve>
    <curve>
        <id>secp160r1</id>
        <bits>160</bits>
        <field>prime</field>
        <file>secp160r1.csv</file>
    </curve>
    <curve>
        <id>secp160r2</id>
        <bits>160</bits>
        <field>prime</field>
        <file>secp160r2.csv</file>
    </curve>
    <curve>
        <id>secp192k1</id>
        <bits>192</bits>
        <field>prime</field>
        <file>secp192k1.csv</file>
    </curve>
    <curve>
        <id>secp192r1</id>
        <bits>192</bits>
        <field>prime</field>
        <file>secp192r1.csv</file>
    </curve>
    <curve>
        <id>secp224r1</id>
        <bits>224</bits>
        <field>prime</field>
        <file>secp224r1.csv</file>
    </curve>
    <curve>
        <id>secp256k1</id>
        <bits>256</bits>
        <field>prime</field>
        <file>secp256k1.csv</file>
    </curve>
    <curve>
        <id>secp256r1</id>
        <bits>256</bits>
        <field>prime</field>
        <file>secp256r1.csv</file>
    </curve>
    <curve>
        <id>secp384r1</id>
        <bits>384</bits>
        <field>prime</field>
        <file>secp384r1.csv</file>
    </curve>
    <curve>
        <id>secp521r1</id>
        <bits>521</bits>
        <field>prime</field>
        <file>secp521r1.csv</file>
    </curve>

    <curve>
        <id>sect163k1</id>
        <bits>163</bits>
        <field>binary</field>
        <file>sect163k1.csv</file>
    </curve>
    <curve>
        <id>sect163r1</id>
        <bits>163</bits>
        <field>binary</field>
        <file>sect163r1.csv</file>
    </curve>
    <curve>
        <id>sect163r2</id>
        <bits>163</bits>
        <field>binary</field>
        <file>sect163r2.csv</file>
    </curve>
    <curve>
        <id>sect233k1</id>
        <bits>233</bits>
        <field>binary</field>
        <file>sect233k1.csv</file>
    </curve>
    <curve>
        <id>sect233r1</id>
        <bits>233</bits>
        <field>binary</field>
        <file>sect233r1.csv</file>
    </curve>
    <curve>
        <id>sect239k1</id>
        <bits>233</bits>
        <field>binary</field>
        <file>sect239k1.csv</file>
    </curve>
    <curve>
        <id>sect283k1</id>
        <bits>283</bits>
        <field>binary</field>
        <file>sect283k1.csv</file>
    </curve>
    <curve>
        <id>sect283r1</id>
        <bits>283</bits>
        <field>binary</field>
        <file>sect283r1.csv</file>
    </curve>
    <curve>
        <id>sect409k1</id>
        <bits>409</bits>
        <field>binary</field>
        <file>sect409k1.csv</file>
    </curve>
    <curve>
        <id>sect409r1</id>
        <bits>409</bits>
        <field>binary</field>
        <file>sect409r1.csv</file>
    </curve>
    <curve>
        <id>sect571k1</id>
        <bits>571</bits>
        <field>binary</field>
        <file>sect571k1.csv</file>
    </curve>
    <curve>
        <id>sect571r1</id>
        <bits>571</bits>
        <field>binary</field>
        <file>sect571r1.csv</file>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/gost/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>gost256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>gost256.csv</file>
    </curve>
    <curve>
        <id>gost512</id>
        <bits>512</bits>
        <field>prime</field>
        <file>gost512.csv</file>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/test/results.xml
<?xml version="1.0" encoding="utf-8" ?>
<results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../schema.xsd">
    <kaResult>
        <id>secp160r1-dh</id>
        <ka>DH</ka>
        <file>secg/secp160r1-dh-sha1.csv</file>
        <curve>secg/secp160r1</curve>
        <onekey>test/secp160r1-U</onekey>
        <otherkey>test/secp160r1-V</otherkey>
    </kaResult>
    <kaResult>
        <id>sect163k1-dh</id>
        <ka>DH</ka>
        <file>secg/sect163k1-dh-sha1.csv</file>
        <curve>secg/sect163k1</curve>
        <onekey>test/sect163k1-U</onekey>
        <otherkey>test/sect163k1-V</otherkey>
    </kaResult>

    <kaResult>
        <id>brainpoolP224r1-dh</id>
        <ka>DH</ka>
        <file>brainpool/brainpoolP224r1-dh-sha1.csv</file>
        <curve>brainpool/brainpoolP224r1</curve>
        <onekey>test/brainpoolP224r1-A</onekey>
        <otherkey>test/brainpoolP224r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP256r1-dh</id>
        <ka>DH</ka>
        <file>brainpool/brainpoolP256r1-dh-sha1.csv</file>
        <curve>brainpool/brainpoolP256r1</curve>
        <onekey>test/brainpoolP256r1-A</onekey>
        <otherkey>test/brainpoolP256r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP384r1-dh</id>
        <ka>DH</ka>
        <file>brainpool/brainpoolP384r1-dh-sha1.csv</file>
        <curve>brainpool/brainpoolP384r1</curve>
        <onekey>test/brainpoolP384r1-A</onekey>
        <otherkey>test/brainpoolP384r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP512r1-dh</id>
        <ka>DH</ka>
        <file>brainpool/brainpoolP512r1-dh-sha1.csv</file>
        <curve>brainpool/brainpoolP512r1</curve>
        <onekey>test/brainpoolP512r1-A</onekey>
        <otherkey>test/brainpoolP512r1-B</otherkey>
    </kaResult>

    <kaResult>
        <id>b163-dhc</id>
        <ka>DHC</ka>
        <file>nist/b163-dhc-sha1.csv</file>
        <curve>nist/B-163</curve>
        <onekey>test/b163-A</onekey>
        <otherkey>test/b163-B</otherkey>
    </kaResult>
    <kaResult>
        <id>b233-dhc</id>
        <ka>DHC</ka>
        <file>nist/b233-dhc-sha1.csv</file>
        <curve>nist/B-233</curve>
        <onekey>test/b233-A</onekey>
        <otherkey>test/b233-B</otherkey>
    </kaResult>
    <kaResult>
        <id>b283-dhc</id>
        <ka>DHC</ka>
        <file>nist/b283-dhc-sha1.csv</file>
        <curve>nist/B-283</curve>
        <onekey>test/b283-A</onekey>
        <otherkey>test/b283-B</otherkey>
    </kaResult>
    <kaResult>
        <id>b409-dhc</id>
        <ka>DHC</ka>
        <file>nist/b409-dhc-sha1.csv</file>
        <curve>nist/B-409</curve>
        <onekey>test/b409-A</onekey>
        <otherkey>test/b409-B</otherkey>
    </kaResult>
    <kaResult>
        <id>b571-dhc</id>
        <ka>DHC</ka>
        <file>nist/b571-dhc-sha1.csv</file>
        <curve>nist/B-571</curve>
        <onekey>test/b571-A</onekey>
        <otherkey>test/b571-B</otherkey>
    </kaResult>
    <kaResult>
        <id>k163-dhc</id>
        <ka>DHC</ka>
        <file>nist/k163-dhc-sha1.csv</file>
        <curve>nist/B-163</curve>
        <onekey>test/k163-A</onekey>
        <otherkey>test/k163-B</otherkey>
    </kaResult>
    <kaResult>
        <id>k233-dhc</id>
        <ka>DHC</ka>
        <file>nist/k233-dhc-sha1.csv</file>
        <curve>nist/B-233</curve>
        <onekey>test/k233-A</onekey>
        <otherkey>test/k233-B</otherkey>
    </kaResult>
    <kaResult>
        <id>k283-dhc</id>
        <ka>DHC</ka>
        <file>nist/k283-dhc-sha1.csv</file>
        <curve>nist/B-283</curve>
        <onekey>test/k283-A</onekey>
        <otherkey>test/k283-B</otherkey>
    </kaResult>
    <kaResult>
        <id>k409-dhc</id>
        <ka>DHC</ka>
        <file>nist/k409-dhc-sha1.csv</file>
        <curve>nist/B-409</curve>
        <onekey>test/k409-A</onekey>
        <otherkey>test/k409-B</otherkey>
    </kaResult>
    <kaResult>
        <id>k571-dhc</id>
        <ka>DHC</ka>
        <file>nist/k571-dhc-sha1.csv</file>
        <curve>nist/B-571</curve>
        <onekey>test/k571-A</onekey>
        <otherkey>test/k571-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p192-dhc</id>
        <ka>ANY</ka>
        <file>nist/p192-dhc-sha1.csv</file>
        <curve>nist/P-192</curve>
        <onekey>test/p192-A</onekey>
        <otherkey>test/p192-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p224-dhc</id>
        <ka>ANY</ka>
        <file>nist/p224-dhc-sha1.csv</file>
        <curve>nist/P-224</curve>
        <onekey>test/p224-A</onekey>
        <otherkey>test/p224-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p256-dhc</id>
        <ka>ANY</ka>
        <file>nist/p256-dhc-sha1.csv</file>
        <curve>nist/P-256</curve>
        <onekey>test/p256-A</onekey>
        <otherkey>test/p256-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p384-dhc</id>
        <ka>ANY</ka>
        <file>nist/p384-dhc-sha1.csv</file>
        <curve>nist/P-384</curve>
        <onekey>test/p384-A</onekey>
        <otherkey>test/p384-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p521-dhc</id>
        <ka>ANY</ka>
        <file>nist/p521-dhc-sha1.csv</file>
        <curve>nist/P-521</curve>
        <onekey>test/p521-A</onekey>
        <otherkey>test/p521-B</otherkey>
    </kaResult>
    <kaResult>
        <id>secp160r1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>secg/secp160r1-dh-raw.csv</file>
        <curve>secg/secp160r1</curve>
        <onekey>test/secp160r1-U</onekey>
        <otherkey>test/secp160r1-V</otherkey>
    </kaResult>
    <kaResult>
        <id>sect163k1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>secg/sect163k1-dh-raw.csv</file>
        <curve>secg/sect163k1</curve>
        <onekey>test/sect163k1-U</onekey>
        <otherkey>test/sect163k1-V</otherkey>
    </kaResult>

    <kaResult>
        <id>brainpoolP224r1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>brainpool/brainpoolP224r1-dh-raw.csv</file>
        <curve>brainpool/brainpoolP224r1</curve>
        <onekey>test/brainpoolP224r1-A</onekey>
        <otherkey>test/brainpoolP224r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP256r1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>brainpool/brainpoolP256r1-dh-raw.csv</file>
        <curve>brainpool/brainpoolP256r1</curve>
        <onekey>test/brainpoolP256r1-A</onekey>
        <otherkey>test/brainpoolP256r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP384r1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>brainpool/brainpoolP384r1-dh-raw.csv</file>
        <curve>brainpool/brainpoolP384r1</curve>
        <onekey>test/brainpoolP384r1-A</onekey>
        <otherkey>test/brainpoolP384r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>brainpoolP512r1-dh-plain</id>
        <ka>DH_PLAIN</ka>
        <file>brainpool/brainpoolP512r1-dh-raw.csv</file>
        <curve>brainpool/brainpoolP512r1</curve>
        <onekey>test/brainpoolP512r1-A</onekey>
        <otherkey>test/brainpoolP512r1-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p192-dhc-plain</id>
        <ka>DH_PLAIN</ka>
        <file>nist/p192-dhc-raw.csv</file>
        <curve>nist/P-192</curve>
        <onekey>test/p192-A</onekey>
        <otherkey>test/p192-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p224-dhc-plain</id>
        <ka>DH_PLAIN</ka>
        <file>nist/p224-dhc-raw.csv</file>
        <curve>nist/P-224</curve>
        <onekey>test/p224-A</onekey>
        <otherkey>test/p224-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p256-dhc-plain</id>
        <ka>DH_PLAIN</ka>
        <file>nist/p256-dhc-raw.csv</file>
        <curve>nist/P-256</curve>
        <onekey>test/p256-A</onekey>
        <otherkey>test/p256-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p384-dhc-plain</id>
        <ka>DH_PLAIN</ka>
        <file>nist/p384-dhc-raw.csv</file>
        <curve>nist/P-384</curve>
        <onekey>test/p384-A</onekey>
        <otherkey>test/p384-B</otherkey>
    </kaResult>
    <kaResult>
        <id>p521-dhc-plain</id>
        <ka>DH_PLAIN</ka>
        <file>nist/p521-dhc-raw.csv</file>
        <curve>nist/P-521</curve>
        <onekey>test/p521-A</onekey>
        <otherkey>test/p521-B</otherkey>
    </kaResult>
</results>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/other/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>M-221</id>
        <bits>221</bits>
        <field>prime</field>
        <file>m221.csv</file>
        <desc>Montgomery M-221 curve from eprint 2013/647, transformed into short Weierstrass form</desc>
    </curve>
    <curve>
        <id>M-383</id>
        <bits>383</bits>
        <field>prime</field>
        <file>m383.csv</file>
        <desc>Montgomery M-383 curve from eprint 2013/647, transformed into short Weierstrass form</desc>
    </curve>
    <curve>
        <id>M-511</id>
        <bits>511</bits>
        <field>prime</field>
        <file>m511.csv</file>
        <desc>Montgomery M-511 curve from eprint 2013/647, transformed into short Weierstrass form</desc>
    </curve>

    <curve>
        <id>Curve25519</id>
        <bits>256</bits>
        <field>prime</field>
        <file>curve25519.csv</file>
        <desc>Curve25519 transformed into short Weierstrass form</desc>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/brainpool/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>brainpoolP160r1</id>
        <bits>160</bits>
        <field>prime</field>
        <file>brainpoolP160r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP160t1</id>
        <bits>160</bits>
        <field>prime</field>
        <file>brainpoolP160t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP192r1</id>
        <bits>192</bits>
        <field>prime</field>
        <file>brainpoolP192r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP192t1</id>
        <bits>192</bits>
        <field>prime</field>
        <file>brainpoolP192t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP224r1</id>
        <bits>224</bits>
        <field>prime</field>
        <file>brainpoolP224r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP224t1</id>
        <bits>224</bits>
        <field>prime</field>
        <file>brainpoolP224t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP256r1</id>
        <bits>256</bits>
        <field>prime</field>
        <file>brainpoolP256r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP256t1</id>
        <bits>256</bits>
        <field>prime</field>
        <file>brainpoolP256t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP320r1</id>
        <bits>320</bits>
        <field>prime</field>
        <file>brainpoolP320r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP320t1</id>
        <bits>320</bits>
        <field>prime</field>
        <file>brainpoolP320t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP384r1</id>
        <bits>384</bits>
        <field>prime</field>
        <file>brainpoolP384r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP384t1</id>
        <bits>384</bits>
        <field>prime</field>
        <file>brainpoolP384t1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP512r1</id>
        <bits>512</bits>
        <field>prime</field>
        <file>brainpoolP512r1.csv</file>
    </curve>
    <curve>
        <id>brainpoolP512t1</id>
        <bits>512</bits>
        <field>prime</field>
        <file>brainpoolP512t1.csv</file>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/bn/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>bn158</id>
        <bits>158</bits>
        <field>prime</field>
        <file>bn158.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn190</id>
        <bits>190</bits>
        <field>prime</field>
        <file>bn190.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn222</id>
        <bits>222</bits>
        <field>prime</field>
        <file>bn222.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn254</id>
        <bits>254</bits>
        <field>prime</field>
        <file>bn254.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn286</id>
        <bits>286</bits>
        <field>prime</field>
        <file>bn286.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn318</id>
        <bits>318</bits>
        <field>prime</field>
        <file>bn318.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn350</id>
        <bits>350</bits>
        <field>prime</field>
        <file>bn350.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn382</id>
        <bits>382</bits>
        <field>prime</field>
        <file>bn382.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn414</id>
        <bits>414</bits>
        <field>prime</field>
        <file>bn414.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn446</id>
        <bits>446</bits>
        <field>prime</field>
        <file>bn446.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn478</id>
        <bits>478</bits>
        <field>prime</field>
        <file>bn478.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn510</id>
        <bits>510</bits>
        <field>prime</field>
        <file>bn510.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn542</id>
        <bits>542</bits>
        <field>prime</field>
        <file>bn542.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn574</id>
        <bits>574</bits>
        <field>prime</field>
        <file>bn574.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn606</id>
        <bits>606</bits>
        <field>prime</field>
        <file>bn606.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
    <curve>
        <id>bn638</id>
        <bits>638</bits>
        <field>prime</field>
        <file>bn638.csv</file>
        <desc>Barreto-Naehrig curve from eprint 2010/429.</desc>
    </curve>
</curves>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/misc/results.xml
<?xml version="1.0" encoding="utf-8" ?>
<results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../schema.xsd">
    <kaResult>
        <id>openssl-bug</id>
        <ka>DH</ka>
        <inline>0xdb6f7cd6a06846bf9da9b4928caa5e4b7c8f58d9</inline>
        <!-- == SHA1(0x1D0F27241C177385B0D5025029FABD5D5D8475DA4E267DCD177B49C63605C25A) -->
        <curve>secg/secp256r1</curve>
        <onekey>misc/openssl-bug/pkey</onekey>
        <otherkey>misc/openssl-bug/skey</otherkey>
        <desc>https://eprint.iacr.org/2011/633</desc>
    </kaResult>
</results>

=== crocs-muni/ECTester/common/src/main/resources/cz/crcs/ectester/data/nist/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>P-192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>p192.csv</file>
    </curve>
    <curve>
        <id>P-224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>p224.csv</file>
    </curve>
    <curve>
        <id>P-256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>p256.csv</file>
    </curve>
    <curve>
        <id>P-384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>p384.csv</file>
    </curve>
    <curve>
        <id>P-521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>p521.csv</file>
    </curve>
    
    <curve>
        <id>K-163</id>
        <bits>163</bits>
        <field>binary</field>
        <file>k163.csv</file>
    </curve>
    <curve>
        <id>B-163</id>
        <bits>163</bits>
        <field>binary</field>
        <file>b163.csv</file>
    </curve>
    <curve>
        <id>K-233</id>
        <bits>233</bits>
        <field>binary</field>
        <file>k233.csv</file>
    </curve>
    <curve>
        <id>B-233</id>
        <bits>233</bits>
        <field>binary</field>
        <file>b233.csv</file>
    </curve>
    <curve>
        <id>K-283</id>
        <bits>283</bits>
        <field>binary</field>
        <file>k283.csv</file>
    </curve>
    <curve>
        <id>B-283</id>
        <bits>283</bits>
        <field>binary</field>
        <file>b283.csv</file>
    </curve>
    <curve>
        <id>K-409</id>
        <bits>409</bits>
        <field>binary</field>
        <file>k409.csv</file>
    </curve>
    <curve>
        <id>B-409</id>
        <bits>409</bits>
        <field>binary</field>
        <file>b409.csv</file>
    </curve>
    <curve>
        <id>K-571</id>
        <bits>571</bits>
        <field>binary</field>
        <file>k571.csv</file>
    </curve>
    <curve>
        <id>B-571</id>
        <bits>571</bits>
        <field>binary</field>
        <file>b571.csv</file>
    </curve>
</curves>
